# Generated by Django 3.0.6 on 2020-05-12 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('datetimeofincedent', models.CharField(max_length=25)),
                ('dateofreg', models.DateField(blank=True, default=datetime.date.today)),
                ('timeofreg', models.TimeField(auto_now_add=True)),
                ('typeComplaint', models.CharField(max_length=50)),
                ('section', models.CharField(default='Section-99', max_length=25)),
                ('status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
    ]
