# Generated by Django 3.0.6 on 2020-05-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firregister',
            name='timeofreg',
            field=models.TimeField(auto_now=True),
        ),
    ]
