# Generated by Django 3.0.6 on 2020-05-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firregister', '0003_auto_20200512_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firregister',
            name='timeofreg',
        ),
    ]
