# Generated by Django 3.0.6 on 2020-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firregister', '0004_remove_firregister_timeofreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firregister',
            old_name='datetimeofincedent',
            new_name='incDT',
        ),
        migrations.AlterField(
            model_name='firregister',
            name='age',
            field=models.CharField(max_length=25),
        ),
    ]
